language: node_js
node_js:
  - 10
script:
  - npm lint
  - npm test:unit
cache:
  directories:
    - "node_modules"
deploy:
  provider: npm
  email: echoulen@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
